### ISSUE TITLE
[v2.8.0] forseti model list send an error when there is no model

### ISSUE THREAD

**Issue by BrunoReboul** [forseti-security/forseti-security#2291]
- version v2.8.0
- module = model
- error

forseti model list
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 707, in channel_spin
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 174, in handle_event
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get_fork_epoch'

Deployed with deployment manager

**Comment by hshin-g** [comment]
@BrunoReboul Can you list the commands you ran before `forseti model list`? 

Additionally, do you have a handle on our Forseti Security Slack? We can work through troubleshooting  this issue on our Slack here: https://join.slack.com/t/forsetisecurity/shared_invite/enQtNDIyMzg4Nzg1NjcxLTJhYjI1YzY0MDg4YjRhMDhhZTMwZTg0MWExZjU1MTNiNWFmMmFlMWQ0MmI3OTE1MzczZTMwNTEzNDZiNDY3NTY

**Comment by ocervell** [comment]
Seeing the same from time to time, using `forseti scanner run`:

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 786, in channel_spin
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 173, in handle_event
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get_fork_epoch'
```

**Comment by dekuhn** [comment]
This issue is stale and has not had any recent activity. If this is still a concern please reopen the issue. Thanks!
