### ISSUE TITLE
BUG ? Error running scanner: IapScanner

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [forseti-security/forseti-security#2708]
2019-04-03 10:46:10,952 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Looking for IAP violations: IapResource(project_full_name=u'organization/899064685583/folder/457815117631/folder/150093548869/folder/736583365201/folder/371694806870/project/manawa-euw4-dtp/', backend_service=backendservice<id=333020148442725244,parent=None>, alternate_services=set([]), direct_access_sources=set([u'0.0.0.0/0']), iap_enabled=False)
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Ancestors of resource: [project<id=manawa-euw4-dtp,parent=None>, folder<id=371694806870,parent=None>, folder<id=736583365201,parent=None>, folder<id=150093548869,parent=None>, folder<id=457815117631,parent=None>, organization<id=899064685583,parent=None>]
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for project<id=manawa-euw4-dtp,parent=None>: []
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=371694806870,parent=None>: []
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=736583365201,parent=None>: []
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=150093548869,parent=None>: []
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=457815117631,parent=None>: []
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for organization<id=899064685583,parent=None>: [IapResourceRules<resource=organization<id=*,parent=None>, rules=set([IapRule<rule_name=Forbid any IAP bypasses (when IAP is enabled), rule_index=0, allowed_alternate_services=[], allowed_direct_access_sources=[], allowed_iap_enabled=^.*$>]), applies_to=self_and_children, inherit_from_parents=True>]
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Does IapResourceRules<resource=organization<id=*,parent=None>, rules=set([IapRule<rule_name=Forbid any IAP bypasses (when IAP is enabled), rule_index=0, allowed_alternate_services=[], allowed_direct_access_sources=[], allowed_iap_enabled=^.*$>]), applies_to=self_and_children, inherit_from_parents=True> apply to resource? True
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Has enabled violation? '^.*$' / False
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Enabled violation: False
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Has alternate service violation? False / [] / set([])
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Alternate services violations: []
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Has sources violation? False / [] / set([u'0.0.0.0/0'])
2019-04-03 10:46:10,955 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Sources violations: []
2019-04-03 10:46:10,955 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Returning violations: []
2019-04-03 10:46:11,065 ERROR [forseti-security][2.13.0] google.cloud.forseti.scanner.scanner(run): Error running scanner: IapScanner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 117, in run
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 642, in run
    all_violations, _ = self._find_violations(iap_data)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 627, in _find_violations
    for (iap_resources, project_resource_counts) in iap_data:
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 610, in _retrieve
    run_data.make_iap_resource(backend, parent.full_name))
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 300, in make_iap_resource
    backend_service, instance_group)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 141, in instance_group_network_port
    project_id=instance_group.project_id),
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/common/gcp_type/network.py", line 64, in from_url
    if '://' not in url:
TypeError: argument of type 'NoneType' is not iterable

**Comment by jf-marquis-Adeo** [comment]
?????
on slack you ask me to create an issue and once it has been created you close it ????

Envoyé de mon iPhone

Le 4 avr. 2019 à 19:19, Darrell Kuhn <notifications@github.com<mailto:notifications@github.com>> a écrit :


Closed #2708<https://github.com/GoogleCloudPlatform/forseti-security/issues/2708>.

**Comment by dekuhn** [comment]
Reopening the issue due to accidental closure.

Marquis my apologizes this was my fault and was not intended. Github project automation closed the issue when I removed it from scope of the review project. This was unexpected and I am sorry for any confusion or frustration I might have caused.

**Comment by osandoval011** [comment]
@jf-marquis-Adeo Hi Marquis, can you please provide me with your slack name.  I would like to confirm I understand all the details revolving your issue so I can solve it efficiently

**Comment by jf-marquis-Adeo** [comment]
jfm or jean-francois.marquis

Envoyé de mon iPhone

Le 23 avr. 2019 à 20:26, osandoval011 <notifications@github.com<mailto:notifications@github.com>> a écrit :


@jf-marquis-Adeo<https://github.com/jf-marquis-Adeo> Hi Marquis, can you please provide me with your slack name. I would like to confirm I understand all the details revolving your issue so I can solve it efficiently

**Comment by osandoval011** [comment]
@jf-marquis-Adeo Can you please confirm this is no longer an issue for you since terraform install?

**Comment by jf-marquis-Adeo** [comment]
yes no more issue
