### ISSUE TITLE
Flaky tests cases causing Travis CI build to fail intermittently

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2856]
Fails on unit tests and pylint, unit tests worked locally and one of the travis push/pr also passed. If I were to update the unit test according to the output, it will fail the other one. Not sure if this is a problem on how we setup travis push/pr.

Note: if you re run it multiple times, it **might** pass once in a while.

Example error output:

```
======================================================================
FAIL: test_cud_firewall_rule_read_only_0_delete (tests.common.gcp_api.compute_test.ComputeTest)
Test create/patch/update/delete firewall rule [with name='delete', verb='delete'].
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/forseti-security/.eggs/parameterized-0.6.1-py3.6.egg/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/forseti-security/tests/common/gcp_api/compute_test.py", line 170, in test_cud_firewall_rule_read_only
    self.assertDictEqual(expected_result, results)
AssertionError: {'tar[14 chars]ps://www.googleapis.com/compute/v1/projects/pr[121 chars] 100} != {'tar[14 chars]ps://compute.googleapis.com/compute/v1/project[125 chars] 100}
  {'name': 'fake-firewall',
   'operationType': 'delete',
   'progress': 100,
   'status': 'DONE',
-  'targetLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^
+  'targetLink': 'https://compute.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^^^^^
======================================================================
FAIL: test_cud_firewall_rule_read_only_1_insert (tests.common.gcp_api.compute_test.ComputeTest)
Test create/patch/update/delete firewall rule [with name='insert', verb='insert'].
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/forseti-security/.eggs/parameterized-0.6.1-py3.6.egg/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/forseti-security/tests/common/gcp_api/compute_test.py", line 170, in test_cud_firewall_rule_read_only
    self.assertDictEqual(expected_result, results)
AssertionError: {'tar[14 chars]ps://www.googleapis.com/compute/v1/projects/pr[121 chars] 100} != {'tar[14 chars]ps://compute.googleapis.com/compute/v1/project[125 chars] 100}
  {'name': 'fake-firewall',
   'operationType': 'insert',
   'progress': 100,
   'status': 'DONE',
-  'targetLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^
+  'targetLink': 'https://compute.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^^^^^
======================================================================
FAIL: test_cud_firewall_rule_read_only_2_patch (tests.common.gcp_api.compute_test.ComputeTest)
Test create/patch/update/delete firewall rule [with name='patch', verb='patch'].
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/forseti-security/.eggs/parameterized-0.6.1-py3.6.egg/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/forseti-security/tests/common/gcp_api/compute_test.py", line 170, in test_cud_firewall_rule_read_only
    self.assertDictEqual(expected_result, results)
AssertionError: {'tar[14 chars]ps://www.googleapis.com/compute/v1/projects/pr[120 chars] 100} != {'tar[14 chars]ps://compute.googleapis.com/compute/v1/project[124 chars] 100}
  {'name': 'fake-firewall',
   'operationType': 'patch',
   'progress': 100,
   'status': 'DONE',
-  'targetLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^
+  'targetLink': 'https://compute.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^^^^^
======================================================================
FAIL: test_cud_firewall_rule_read_only_3_update (tests.common.gcp_api.compute_test.ComputeTest)
Test create/patch/update/delete firewall rule [with name='update', verb='update'].
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/forseti-security/.eggs/parameterized-0.6.1-py3.6.egg/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/forseti-security/tests/common/gcp_api/compute_test.py", line 170, in test_cud_firewall_rule_read_only
    self.assertDictEqual(expected_result, results)
AssertionError: {'tar[14 chars]ps://www.googleapis.com/compute/v1/projects/pr[121 chars] 100} != {'tar[14 chars]ps://compute.googleapis.com/compute/v1/project[125 chars] 100}
  {'name': 'fake-firewall',
   'operationType': 'update',
   'progress': 100,
   'status': 'DONE',
-  'targetLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^
+  'targetLink': 'https://compute.googleapis.com/compute/v1/projects/project1/global/firewalls/fake-firewall'}
?                         ^^^^^^^
----------------------------------------------------------------------
Ran 1197 tests in 87.897s
FAILED (failures=4, skipped=2)
The command "./install/scripts/docker_unittest_forseti.sh" exited with 1.
141.38s$ ./install/scripts/docker_pystyle_forseti.sh
Running pylint... 
Using config file /forseti-security/pylintrc
************* Module install.gcp_installer
I: 19, 0: Useless suppression of 'import-error' (useless-suppression)
------------------------------------
Your code has been rated at 10.00/10


```

**Comment by dekuhn** [comment]
@joecheuk Can we use this issue to track our flaky test cases which need to be improved.

**Comment by katze120** [comment]
I ran into the same issue with test_cud_firewall_rule_read_only tests in the last 2 days, occasionally passing these tests but failing most of the time.

My conclusion:

- Looks like this is due to googleapiclient.discovery.build returning different _baseUrl intermittently

- According to [this block](https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery.py#L218-L231)  and [this block](https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery.py#L87-L91) in discovery.py, www.googleapis.com should be returned as baseUrl if it's working, else it'll return {api}.googleapis.com

Here're the functions involved which lead to the above conclusion:

- test_cud_firewall_rule_read_only calls ComputeClient functions in ./google/cloud/forseti/common/gcp_api/compute.py

- The {verb}_firewall_rule functions here calls the corresponding verb functions in google/cloud/forseti/common/gcp_api/repository_mixins.py

- When read_only is true, verb functions in repository_mixins.py calls _create_fake_operation, which takes input resource_link and output as targetLink

- _build_resource_link function in BaseRepositoryClient shows how resource link is built. It takes self.gcp_service._baseUrl as part of input. 

- gcp_service comes from function _create_service_api function, which calls  [googleapiclient.discovery.build](https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery.py#L169)
