### ISSUE TITLE
Make forseti version easier to access

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2857]
maybe we can include --version flag to show the version.

**Comment by red2k18** [comment]
Is this really needed? Version can currently be viewed on Stackdriver logging.

**Comment by divc99** [comment]
Can I work on it?

**Comment by TravisDavis-ops** [comment]
Is this still up for grabs

**Comment by red2k18** [comment]
@garrettwong are you working on this?

**Comment by garrettwong** [comment]
@TravisDavis-ops TravisDavis-ops - sorry for the delayed response, feel free to take this.  If not, I'll revisit in a week.

**Comment by gkowalski-google** [comment]
This was merged in but does not appear to be working:
```
Traceback (most recent call last):
  File "/usr/local/bin/forseti", line 11, in <module>
    load_entry_point('forseti-security==2.25.1', 'console_scripts', 'forseti')()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/stubs.py", line 34, in RunForsetiCli
    forseti_cli.main()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/services/cli.py", line 1232, in main
    services[config.service](client, config, output, config_env)
TypeError: run_version() takes 0 positional arguments but 4 were given
```
