### ISSUE TITLE
Forseti installer broken

### ISSUE THREAD

**Issue by umairidris** [forseti-security/forseti-security#2862]
$ python3 /tmp/tmp9x6jw11z/install/gcp_installer.py --no-cloudshell

Traceback (most recent call last):
  File "/tmp/tmp9x6jw11z/install/gcp_installer.py", line 23, in <module>
    gcp_installer.run()
  File "/tmp/tmp9x6jw11z/install/gcp/gcp_installer.py", line 28, in run
    site.main() # Load up the package
  File "/usr/lib/python3.6/site.py", line 542, in main
    abs_paths()
  File "/usr/lib/python3.6/site.py", line 116, in abs_paths
    m.__cached__ = os.path.abspath(m.__cached__)
  File "/usr/lib/python3.6/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/local/google/home/umairidris/.cache/bazel/_bazel_umairidris/bb44e7b82d7aca2ed3dc5047e4c85f5a/execroot/__main__/bazel-out/k8-fastbuild/bin/deploy/create_project.runfiles/__main__/deploy/create_project.py", line 917, in setup_project
    output = step.func(config)
  File "/usr/local/google/home/umairidris/.cache/bazel/_bazel_umairidris/bb44e7b82d7aca2ed3dc5047e4c85f5a/execroot/__main__/bazel-out/k8-fastbuild/bin/deploy/create_project.runfiles/__main__/deploy/create_project.py", line 948, in install_forseti
    forseti.install(forseti_config)
  File "/usr/local/google/home/umairidris/.cache/bazel/_bazel_umairidris/bb44e7b82d7aca2ed3dc5047e4c85f5a/execroot/__main__/bazel-out/k8-fastbuild/bin/deploy/create_project.runfiles/__main__/deploy/utils/forseti.py", line 65, in install
    runner.run_command(install_cmd)
  File "/usr/local/google/home/umairidris/.cache/bazel/_bazel_umairidris/bb44e7b82d7aca2ed3dc5047e4c85f5a/execroot/__main__/bazel-out/k8-fastbuild/bin/deploy/create_project.runfiles/__main__/deploy/utils/runner.py", line 38, in run_command
    run(subprocess.check_call, cmd)
  File "/usr/local/google/home/umairidris/.cache/bazel/_bazel_umairidris/bb44e7b82d7aca2ed3dc5047e4c85f5a/execroot/__main__/bazel-out/k8-fastbuild/bin/deploy/create_project.runfiles/__main__/deploy/utils/runner.py", line 29, in run
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '/tmp/tmp9x6jw11z/install/gcp_installer.py', '--no-cloudshell']' returned non-zero exit status 1.

**Comment by dekuhn** [comment]
@joecheuk @red2k18  can we please ensure our release testing includes this type of installer test going forward.

**Comment by dekuhn** [comment]
@joecheuk Does this fix need to be back-ported to previous versions?

**Comment by red2k18** [comment]
@blueandgold do we need to backport this to previous versions or close this issue?

**Comment by joecheuk** [comment]
This issue is py3 only, no need to backport.

**Comment by umairidris** [comment]
@joecheuk has the fix been backported to dev from 2.16?

**Comment by joecheuk** [comment]
almost - once this PR is in https://github.com/forseti-security/forseti-security/pull/2877

**Comment by dekuhn** [comment]
@red2k18 @joecheuk I believe this was fixed in 2.16 release if that is the case can we fix the targeted release here as it does not apply to 2.17. 

Thanks.

**Comment by red2k18** [comment]
Fixed it. Thanks Darrel!
