### ISSUE TITLE
Notifier error Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2865]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.15.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/email_violations.py", line 210, in run
    self._send(notification=email_notification)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.15.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/email_violations.py", line 201, in _send
    attachment=attachment)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.15.0-py3.6.egg/google/cloud/forseti/common/util/email/sendgrid_connector.py", line 135, in send
    response = self._execute_send(email)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.15.0-py3.6.egg/google/cloud/forseti/common/util/email/sendgrid_connector.py", line 77, in _execute_send
    return self.sendgrid.client.mail.send.post(request_body=email.get())
  File "/home/ubuntu/forseti-security/.eggs/python_http_client-3.1.0-py3.6.egg/python_http_client/client.py", line 236, in http_request
    kwargs['request_body']).encode('utf-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable"  
 timestamp:  "2019-05-29T02:13:30.602Z"  
```

**Comment by red2k18** [comment]
@joecheuk can this issue be closed?
