### ISSUE TITLE
2.17 - Terraform install -missing variable db_migrator.py 

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [forseti-security/forseti-security#2938]
- [x] Update Forseti db_migrator.py to support custom database name for GCE
- [ ] Update Terraform and Helm Charts to support custom database name on GKE
---

Hello,
after installing 2.17 through terraform with specified db_name
 ` cloudsql_db_name                                    = "forseti-security"`
my forseti refuse to start...
after investigation i see that in /home/ubuntu/forseti-security/install/gcp/upgrade_tools/db_migrator.py database name is hardcoded :
`DEFAULT_DB_CONN_STR = 'mysql://root@127.0.0.1:3306/forseti_security'`
so db_migrator failed
`['/home/ubuntu/forseti-security/install/gcp/upgrade_tools/db_migrator.py']
Traceback (most recent call last):
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 425, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 822, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 554, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 1250, in _do_get
    self._dec_overflow()
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 1247, in _do_get
    return self._create_connection()
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 370, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 499, in __init__
    self.__connect(first_connect_check=True)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 701, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/forseti-security/.eggs/mysqlclient-1.4.2.post1-py3.6-linux-x86_64.egg/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/ubuntu/forseti-security/.eggs/mysqlclient-1.4.2.post1-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1049, "Unknown database 'forseti_security'")`

**Comment by gkowalski-google** [comment]
@jf-marquis-Adeo Are you still having this issue?

**Comment by jf-marquis-Adeo** [comment]
yes sure
db name is written in the code
so if you change the db name with terraform for example db_migrator is not working

Envoyé de mon iPhone

Le 13 sept. 2019 à 18:57, Gregg Kowalski <notifications@github.com<mailto:notifications@github.com>> a écrit :


@jf-marquis-Adeo<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjf-marquis-Adeo&data=02%7C01%7Cjean-francois.marquis%40adeo.com%7C51e6d361c3f7421d0a7d08d7386b6d62%7C9f1db594b8ab4e59b56b4a3c145eaf07%7C1%7C0%7C637039906372616683&sdata=wORmd95hubp5w5pVF1rozMp7fMDJlyrvRQIEB8fTISk%3D&reserved=0> Are you still having this issue?

**Comment by gkowalski-google** [comment]
Hi @jf-marquis-Adeo, this will be fixed with the next release for GCE installations.

**Comment by jf-marquis-Adeo** [comment]
excellent

Envoyé de mon iPhone

**Comment by blueandgold** [comment]
This has been release in Forseti v2.21 release.

**Comment by blueandgold** [comment]
Re-opening, there is one more change needed for GKE.
