### ISSUE TITLE
Investigate why replay unit test failing inconsistently in travis build

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#3117]
The following unit tests fail sometimes and need multiple restart of the build to pass.

```
=====================================================================
ERROR: test_record_and_replay (tests.common.util.replay_test.ReplayTest)
Verify record and replay functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/forseti/forseti-security/tests/common/util/replay_test.py", line 86, in test_record_and_replay
    results = self.run_api_tests(record=False)
  File "/home/forseti/forseti-security/tests/common/util/replay_test.py", line 74, in run_api_tests
    responses.append(gce_api_client.get_project(self.project_id))
  File "/home/forseti/forseti-security/google/cloud/forseti/common/gcp_api/compute.py", line 1309, in get_project
    results = self.repository.projects.get(project_id)
  File "/home/forseti/forseti-security/google/cloud/forseti/common/gcp_api/repository_mixins.py", line 127, in get
    verb_arguments=arguments,
  File "/home/forseti/forseti-security/google/cloud/forseti/common/gcp_api/_base_repository.py", line 516, in execute_query
    return self._execute(request)
  File "/home/forseti/forseti-security/google/cloud/forseti/common/util/replay.py", line 190, in replay_wrapper
    return f(self, request, *args, **kwargs)
  File "/home/forseti/forseti-security/google/cloud/forseti/common/util/replay.py", line 82, in record_wrapper
    return f(self, request, *args, **kwargs)
  File "/home/forseti/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/forseti/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/forseti/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/forseti/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/forseti/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/forseti/forseti-security/google/cloud/forseti/common/gcp_api/_base_repository.py", line 543, in _execute
    num_retries=self._num_retries)
  File "/home/forseti/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/forseti/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/http.py", line 850, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/forseti/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/forseti/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/http.py", line 1678, in request
    resp, content = self._iterable.pop(0)
IndexError: pop from empty list
```

**Comment by kevensen** [comment]
Possibly related to #2856 ?

**Comment by blueandgold** [comment]
The firewall test is related to #2856.  But not the replay test.  Renaming this issue to differentiate.

**Comment by blueandgold** [comment]
A little more information after adding some print statements, looks like the recorded file is not being loaded correctly, and live external api call is made.

![image](https://user-images.githubusercontent.com/6977544/63496498-e3e2fe00-c476-11e9-8ff3-13349dc2f943.png)

**Comment by blueandgold** [comment]
Looks like the request key is not matching.
```
request_key https://compute.googleapis.com/compute/v1/projects/project1?alt=jsonNone
```
```
requests {'https://www.googleapis.com/compute/v1/projects/project1?alt=jsonNone': deque([{'exception_args': None, 'raised': False, 'request': '{"uri": "https://www.googleapis.com/compute/v1/projects/project1?alt=json", "method": "GET", "body": null, "headers": {"accept": "application/json", "accept-encoding": "gzip, deflate", "user-agent": "google-api-python-client/1.7.7 (gzip)", "content-length": "0"}, "methodId": "compute.projects.get", "resumable": null, "response_callbacks": [], "_in_error_state": false, "body_size": 0, "resumable_uri": null, "resumable_progress": 0}', 'result': {'kind': 'compute#project', 'id': '1111111', 'creationTimestamp': '2016-02-25T14:01:23.140-08:00', 'name': 'project1', 'commonInstanceMetadata': {'kind': 'compute#metadata', 'fingerprint': 'ABC', 'items': [{'key': 'some-key', 'value': 'some-value'}]}, 'quotas': [{'metric': 'SNAPSHOTS', 'limit': 1000.0, 'usage': 0.0}, {'metric': 'NETWORKS', 'limit': 5.0, 'usage': 1.0}, {'metric': 'FIREWALLS', 'limit': 100.0, 'usage': 9.0}, {'metric': 'IMAGES', 'limit': 100.0, 'usage': 0.0}, {'metric': 'STATIC_ADDRESSES', 'limit': 8.0, 'usage': 0.0}, {'metric': 'ROUTES', 'limit': 200.0, 'usage': 12.0}, {'metric': 'FORWARDING_RULES', 'limit': 15.0, 'usage': 1.0}, {'metric': 'TARGET_POOLS', 'limit': 50.0, 'usage': 1.0}, {'metric': 'HEALTH_CHECKS', 'limit': 50.0, 'usage': 1.0}, {'metric': 'IN_USE_ADDRESSES', 'limit': 23.0, 'usage': 1.0}, {'metric': 'TARGET_INSTANCES', 'limit': 50.0, 'usage': 0.0}, {'metric': 'TARGET_HTTP_PROXIES', 'limit': 10.0, 'usage': 0.0}, {'metric': 'URL_MAPS', 'limit': 10.0, 'usage': 0.0}, {'metric': 'BACKEND_SERVICES', 'limit': 5.0, 'usage': 0.0}, {'metric': 'INSTANCE_TEMPLATES', 'limit': 100.0, 'usage': 0.0}, {'metric': 'TARGET_VPN_GATEWAYS', 'limit': 5.0, 'usage': 0.0}, {'metric': 'VPN_TUNNELS', 'limit': 10.0, 'usage': 0.0}, {'metric': 'BACKEND_BUCKETS', 'limit': 3.0, 'usage': 0.0}, {'metric': 'ROUTERS', 'limit': 10.0, 'usage': 0.0}, {'metric': 'TARGET_SSL_PROXIES', 'limit': 10.0, 'usage': 0.0}, {'metric': 'TARGET_HTTPS_PROXIES', 'limit': 10.0, 'usage': 0.0}, {'metric': 'SSL_CERTIFICATES', 'limit': 10.0, 'usage': 0.0}, {'metric': 'SUBNETWORKS', 'limit': 100.0, 'usage': 11.0}, {'metric': 'TARGET_TCP_PROXIES', 'limit': 10.0, 'usage': 0.0}, {'metric': 'SECURITY_POLICIES', 'limit': 10.0, 'usage': 0.0}, {'metric': 'SECURITY_POLICY_RULES', 'limit': 1000.0, 'usage': 0.0}], 'selfLink': 'https://www.googleapis.com/compute/v1/projects/project1', 'defaultServiceAccount': '1111111-compute@developer.gserviceaccount.com', 'xpnProjectStatus': 'UNSPECIFIED_XPN_PROJECT_STATUS'}, 'uri': 'https://www.googleapis.com/compute/v1/projects/project1?alt=json'}]), 'https://www.googleapis.com/compute/v1/projects/project1/global/networks?alt=jsonNone': deque([{'exception_args': None, 'raised': False, 'request': '{"uri": "https://www.googleapis.com/compute/v1/projects/project1/global/networks?alt=json", "method": "GET", "body": null, "headers": {"accept": "application/json", "accept-encoding": "gzip, deflate", "user-agent": "google-api-python-client/1.7.7 (gzip)", "content-length": "0"}, "methodId": "compute.networks.list", "resumable": null, "response_callbacks": [], "_in_error_state": false, "body_size": 0, "resumable_uri": null, "resumable_progress": 0}', 'result': {'kind': 'compute#networkList', 'id': 'projects/project1/global/networks', 'items': [{'kind': 'compute#network', 'id': '1234', 'creationTimestamp': '2017-09-25T12:33:24.312-07:00', 'name': 'default1', 'description': 'Default network for the project', 'selfLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/networks/default1', 'autoCreateSubnetworks': True, 'subnetworks': ['https://www.googleapis.com/compute/v1/projects/project1/regions/europe-west1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/asia-east1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/us-west1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/asia-northeast1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/us-central1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/southamerica-east1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/europe-west3/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/us-east1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/us-east4/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/europe-west2/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/asia-southeast1/subnetworks/default1', 'https://www.googleapis.com/compute/v1/projects/project1/regions/australia-southeast1/subnetworks/default1']}], 'nextPageToken': '12345', 'selfLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/networks'}, 'uri': 'https://www.googleapis.com/compute/v1/projects/project1/global/networks?alt=json'}]), 'https://www.googleapis.com/compute/v1/projects/project1/global/networks?alt=json&pageToken=12345None': deque([{'exception_args': None, 'raised': False, 'request': '{"uri": "https://www.googleapis.com/compute/v1/projects/project1/global/networks?alt=json&pageToken=12345", "method": "GET", "body": null, "headers": {"accept": "application/json", "accept-encoding": "gzip, deflate", "user-agent": "google-api-python-client/1.7.7 (gzip)", "content-length": "0"}, "methodId": "compute.networks.list", "resumable": null, "response_callbacks": [], "_in_error_state": false, "body_size": 0, "resumable_uri": null, "resumable_progress": 0}', 'result': {'kind': 'compute#networkList', 'id': 'projects/project1/global/networks', 'items': [{'kind': 'compute#network', 'id': '1234', 'creationTimestamp': '2017-09-25T12:41:09.416-07:00', 'name': 'default2', 'selfLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/networks/default2', 'autoCreateSubnetworks': False, 'subnetworks': ['https://www.googleapis.com/compute/v1/projects/project1/regions/us-central1/subnetworks/default2']}], 'selfLink': 'https://www.googleapis.com/compute/v1/projects/project1/global/networks'}, 'uri': 'https://www.googleapis.com/compute/v1/projects/project1/global/networks?alt=json&pageToken=12345'}]), 'https://www.googleapis.com/compute/v1/projects/project1/aggregated/instances?alt=jsonNone': deque([{'raised': True, 'request': '{"uri": "https://www.googleapis.com/compute/v1/projects/project1/aggregated/instances?alt=json", "method": "GET", "body": null, "headers": {"accept": "application/json", "accept-encoding": "gzip, deflate", "user-agent": "google-api-python-client/1.7.7 (gzip)", "content-length": "0"}, "methodId": "compute.instances.aggregatedList", "resumable": null, "response_callbacks": [], "_in_error_state": false, "body_size": 0, "resumable_uri": null, "resumable_progress": 0}', 'result': <class 'googleapiclient.errors.HttpError'>, 'uri': 'https://www.googleapis.com/compute/v1/projects/project1/aggregated/instances?alt=json', 'exception_args': ({'status': '403', 'content-type': 'application/json'}, b'\n{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "forbidden",\n    "message": "Required \'compute.instances.list\' permission for \'projects/project1\'"\n   }\n  ],\n  "code": 403,\n  "message": "Required \'compute.instances.list\' permission for \'projects/project1\'"\n }\n}\n', 'https://www.googleapis.com/compute/v1/projects/project1/aggregated/instances?alt=json')}])}
```
