### ISSUE TITLE
Config Validator failing when in isolated network environment

### ISSUE THREAD

**Issue by pdutch** [forseti-security/forseti-security#3398]
Version 2.3.0
Config Validator errors when running the scan. Inventory completes fine, CAI export is on the bucket.
Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanner_builder.py", line 99, in _instantiate_scanner
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 21, in <module>
    from google.cloud.forseti.scanner.scanners.config_validator_util import (
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/cv_data_converter.py", line 22, in <module>
    from google.cloud.asset.v1.assets_pb2 import Resource
ModuleNotFoundError: No module named 'google.cloud.asset.v1'; 'google.cloud.asset' is not a package
```
Confirmed 
`-rw-r--r-- 1 root root 12340 Oct 31 23:32 assets_pb2.py`
located in:
`/home/ubuntu/forseti-security/google/cloud/asset/v1`

Deployed manually (via terraform, but not the module). Custom Startup Script:
```
#!/bin/bash
set -eu

# Env variables
USER=ubuntu
USER_HOME=/home/ubuntu
# # INTERNET_CONNECTION="$(ping -q -w1 -c1 google.com &>/dev/null && echo online || echo offline)"
INTERNET_CONNECTION=online
# export PIP_INDEX_URL="https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"


# # Log status of internet connection
# if [ $INTERNET_CONNECTION == "offline" ]; then
#   echo "Forseti Startup - A connection to the internet was not detected."
# fi

# forseti_conf_server digest: ${forseti_conf_server_checksum}
# This digest is included in the startup script to rebuild the Forseti server VM
# whenever the server configuration changes.

# set apt sources
# remove default cloud sdk apt
rm -f /etc/apt/sources.list.d/partner.list

# add ubuntu sources
sed -i 's~http://security.ubuntu.com/ubuntu~https://artifactory.xxx.xxx/artifactory/ubuntu-security~g' /etc/apt/sources.list
sed -i 's~http://australia-southeast1.gce.archive.ubuntu.com/ubuntu~https://artifactory.xxx.xxx/artifactory/au-archive-ubuntu~g' /etc/apt/sources.list

# add artifactory repo for gcloud sdk
if ! [ -e "/etc/apt/sources.list.d/google-cloud-sdk.list" ]; then
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://artifactory.xxx.xxx/artifactory/google-pkg/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  curl https://artifactory.xxx.xxx/artifactory/google-pkg-cache/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
fi

# Ubuntu update.
echo "Forseti Startup - Updating Ubuntu."
sudo apt-get update -y
# sudo apt-get upgrade -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
sudo apt-get update -y
sudo apt-get --assume-yes install google-cloud-sdk git unzip

if ! [ -e "/usr/sbin/google-fluentd" ]; then
  echo "Forseti Startup - Installing GCP Logging agent."
  cd $USER_HOME
  export http_proxy="http://x.x.x.x:80"
  export https_proxy="http://x.x.x.x:80"
  curl -sSO https://dl.google.com/cloudagents/install-logging-agent.sh
  unset http_proxy
  unset https_proxy
  # update repos to point at artifactory
  sed -i "s~REPO_HOST='packages.cloud.google.com'~REPO_HOST='artifactory.xxx.xxx/artifactory/google-pkg'~g" $USER_HOME/install-logging-agent.sh
  sed -i "s~deb\ http:~deb\ https:~g" $USER_HOME/install-logging-agent.sh
  bash $USER_HOME/install-logging-agent.sh
fi

# Check whether Cloud SQL proxy is installed.
if [ -z "$(which cloud_sql_proxy)" ]; then
  echo "Forseti Startup - Installing GCP Cloud SQL Proxy."
  cd $USER_HOME
  export http_proxy="http://x.x.x.x:80"
  export https_proxy="http://x.x.x.x:80"
  wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
  sudo mv cloud_sql_proxy.linux.amd64 /usr/local/bin/cloud_sql_proxy
  chmod +x /usr/local/bin/cloud_sql_proxy
  unset http_proxy
  unset https_proxy
fi

# Install Forseti Security.
cd $USER_HOME
if [ $INTERNET_CONNECTION == "online" ]; then
  rm -rf *forseti*
fi

# Download Forseti source code
echo "Forseti Startup - Cloning Forseti repo."
export http_proxy="http://x.x.x.x:80"
export https_proxy="http://x.x.x.x:80"
git clone --branch v2.23.0 --depth 1 https://github.com/GoogleCloudPlatform/forseti-security
unset http_proxy
unset https_proxy
cd forseti-security

# Forseti host dependencies
echo "Forseti Startup - Installing Forseti linux dependencies."
sudo apt-get install -y $(cat install/dependencies/apt_packages.txt | grep -v "#" | xargs)

# # Forseti dependencies
# echo "Forseti Startup - Installing Forseti python dependencies."
python3 -m pip install --upgrade setuptools wheel -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install --upgrade -r requirements.txt -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"

# Install sqlalchemy-migrate without version constraints first, so the specific version below will install:
python3 -m pip install sqlalchemy-migrate -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"

# Install forseti required packages - specific versions from setup.py
python3 -m pip install anytree==2.4.3 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install google-api-python-client==1.7.10 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install google-auth==1.6.3 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install google-auth-httplib2==0.0.3 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install Jinja2==2.10.1 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install jmespath==0.9.3 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install netaddr==0.7.19 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install pyyaml==4.2b4 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install python-graph-core==1.8.2 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install python-dateutil==2.7.5 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install ratelimiter==1.2.0.post0 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install retrying==1.3.3 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install requests[security]==2.21.0 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install sendgrid==5.6.0 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install simple-crypt==4.1.7 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install unicodecsv==0.14.1 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
# Setup related.
python3 -m pip install grpcio==1.22.0 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install grpcio-tools==1.22.0 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install protobuf==3.9.0 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
# Testing related.
python3 -m pip install parameterized==0.6.1 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install ruamel.yaml==0.15.37 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install pylint==1.9.4 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install pylint-quotes==0.2.1 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install PyMySQL==0.9.3 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install SQLAlchemy==1.2.18 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install sqlalchemy-migrate -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
python3 -m pip install sqlalchemy-migrate==0.11.0 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"

# Optional packages
# python3 -m pip install mailjet-rest==1.3.3 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"
# python3 -m pip install google-cloud-profiler==1.0.8 -i "https://artifactory.xxx.xxx/artifactory/api/pypi/pypi/simple"


# Setup Forseti logging
touch /var/log/forseti.log
chown ubuntu:root /var/log/forseti.log
cp $USER_HOME/forseti-security/configs/logging/fluentd/forseti.conf /etc/google-fluentd/config.d/forseti.conf
cp $USER_HOME/forseti-security/configs/logging/logrotate/forseti /etc/logrotate.d/forseti
chmod 644 /etc/logrotate.d/forseti
service google-fluentd restart
logrotate /etc/logrotate.conf

# Change the access level of configs/ rules/ and run_forseti.sh
chmod -R ug+rwx $USER_HOME/forseti-security/configs $USER_HOME/forseti-security/rules $USER_HOME/forseti-security/install/gcp/scripts/run_forseti.sh

# Install Forseti
echo "Forseti Startup - Installing Forseti python package."
python3 setup.py install

# Export variables required by initialize_forseti_services.sh.
export SQL_PORT=3306
export SQL_INSTANCE_CONN_STRING=forseti-projectid:australia-southeast1:forseti-db-id
export FORSETI_DB_NAME=forseti_security

# Export variables required by run_forseti.sh
export FORSETI_HOME=$USER_HOME/forseti-security
export FORSETI_SERVER_CONF=$USER_HOME/forseti-security/configs/forseti_conf_server.yaml
export POLICY_LIBRARY_HOME=$USER_HOME/policy-library
export POLICY_LIBRARY_SYNC_ENABLED=false
export POLICY_LIBRARY_SYNC_GIT_SYNC_TAG=
export POLICY_LIBRARY_REPOSITORY_URL=
export SCANNER_BUCKET=forseti-bucket

# Store the variables in /etc/profile.d/forseti_environment.sh
# so all the users will have access to them

FORSETI_ENV_FILE="$(cat << EOF
export FORSETI_HOME=$USER_HOME/forseti-security
export FORSETI_SERVER_CONF=$USER_HOME/forseti-security/configs/forseti_conf_server.yaml
export POLICY_LIBRARY_HOME=$USER_HOME/policy-library
export POLICY_LIBRARY_SYNC_ENABLED=false
export POLICY_LIBRARY_SYNC_GIT_SYNC_TAG=
export POLICY_LIBRARY_REPOSITORY_URL=
export SCANNER_BUCKET=forseti-bucket
EOF
)"
echo "$FORSETI_ENV_FILE" > /etc/profile.d/forseti_environment.sh


# Download server configuration from GCS
echo "Forseti Startup - Downloading Forseti configuration from GCS."
gsutil cp gs://forseti-bucket/configs/forseti_conf_server.yaml $USER_HOME/forseti-security/configs/forseti_conf_server.yaml
gsutil cp -r gs://forseti-bucket/rules $USER_HOME/forseti-security/

# Clear out old Config Validator constraints
sudo rm -rf $USER_HOME/policy-library
# Get Config Validator constraints
sudo mkdir -m 777 -p $USER_HOME/policy-library
if [ "false" == "true" ]; then
  # Policy Library Sync
  echo "Forseti Startup - Policy Library sync is enabled."

  # Install Docker
  if [ -z "$(which docker)" ]; then
    echo "Forseti Startup - Installing Docker for the Policy Library sync."
    sudo apt-get update
    sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    sudo apt update
    apt-cache policy docker-ce
    sudo apt install -y docker-ce
  fi

  # Setup local FS
  # Note: gsutil is using the -n flag so that once the SSH key is copied locally, it is not overwritten for any subsequent runs of terraform
  mkdir -p /etc/git-secret
  gsutil cp -n gs://forseti-bucket/${policy_library_sync_gcs_directory_name}/* /etc/git-secret/
else
  # DEPRECATED! Remove once users have migrated over to Git-Sync
  # Download the Newest Config Validator constraints from GCS
  echo "Forseti Startup - Copying Policy Library from GCS."

  # Attempt to download the config-validator policy and gracefully handle the absence
  # of policy files.  The config-validator is not required for the rest of Forseti
  # and should not halt installation.
  gsutil cp -r gs://forseti-bucket/policy-library $USER_HOME/policy-library/ || echo "No policy available, continuing with Forseti installation"
fi

# Start Forseti service depends on vars defined above.
echo "Forseti Startup - Starting services."
bash ./install/gcp/scripts/initialize_forseti_services.sh
systemctl start cloudsqlproxy
if [ "false" == "true" ]; then
  systemctl start policy-library-sync
  sleep 5
fi
systemctl start config-validator
sleep 5

echo "Forseti Startup - Attempting to update database schema, if necessary."
python3 $USER_HOME/forseti-security/install/gcp/upgrade_tools/db_migrator.py

# Start main Forseti service
echo "Forseti Startup - Starting Forseti service."
systemctl start forseti
echo "Forseti Startup - Success! The Forseti API server has been started."

# Create a Forseti env script
FORSETI_ENV="$(cat << EOF
#!/bin/bash

export PATH=$PATH:/usr/local/bin

# Forseti environment variables
export FORSETI_HOME=$USER_HOME/forseti-security
export FORSETI_SERVER_CONF=$USER_HOME/forseti-security/configs/forseti_conf_server.yaml
export POLICY_LIBRARY_HOME=$USER_HOME/policy-library
export POLICY_LIBRARY_SYNC_ENABLED=false
export POLICY_LIBRARY_SYNC_GIT_SYNC_TAG=
export POLICY_LIBRARY_REPOSITORY_URL=
export SCANNER_BUCKET=forseti-bucket
EOF
)"
echo "$FORSETI_ENV" > $USER_HOME/forseti_env.sh

USER=ubuntu
# Use flock to prevent rerun of the same cron job when the previous job is still running.
# If the lock file does not exist under the tmp directory, it will create the file and put a lock on top of the file.
# When the previous cron job is not finished and the new one is trying to run, it will attempt to acquire the lock
# to the lock file and fail because the file is already locked by the previous process.
# The -n flag in flock will fail the process right away when the process is not able to acquire the lock so we won't
# queue up the jobs.
# If the cron job failed the acquire lock on the process, it will log a warning message to syslog.

# commenting out cron for now
# (echo "0 2 * * * (/usr/bin/flock -n $USER_HOME/forseti-security/forseti_cron_runner.lock $USER_HOME/forseti-security/install/gcp/scripts/run_forseti.sh -b forseti-bucket || echo '[forseti-security] Warning: New Forseti cron job will not be started, because previous Forseti job is still running.') 2>&1 | logger") | crontab -u $USER -

echo "Forseti Startup - Added the run_forseti.sh to crontab under user $USER."
echo "Forseti Startup - Execution of startup script finished."
```

The only other errors I've noticed, is on startup:

```
11/1/19, 10:35 AM InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'cai_resource_name'") [SQL: '\nALTER TABLE gcp_inventory ADD cai_resource_name VARCHAR(4096)'] (Background on this error at: http://sqlalche.me/e/2j85)
11/1/19, 10:35 AM InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'cai_resource_type'") [SQL: '\nALTER TABLE gcp_inventory ADD cai_resource_type VARCHAR(512)'] (Background on this error at: http://sqlalche.me/e/2j85)
11/1/19, 10:35 AM InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'violation_message'") [SQL: '\nALTER TABLE violations ADD violation_message TEXT'] (Background on this error at: http://sqlalche.me/e/2j85)
11/1/19, 10:35 AM InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'resource_name'") [SQL: '\nALTER TABLE violations ADD resource_name VARCHAR(256)'] (Background on this error at: http://sqlalche.me/e/2j85)
```

But these errors are present on my test org system which works fine, so I've ignored them for now.

**Comment by kevensen** [comment]
@pdutch Thanks for submitting this issue and providing those details.  In order to help me reproduce the error, could you please answer the following questions?

1. Is this a fresh install of Forseti 2.23 or is it an upgrade?  
2. If this is an upgrade, from what version are you upgrading?
  a. Also, was the previous version installed via the Python installer or Terraform?

**Comment by pdutch** [comment]
It's was an upgrade from v2.22, but that version had the same issue. I've
since rebuilt the vm many times from fresh and gone straight to V2.23. Each
time it's been installed effectively from the startup script. I've cobbled
together my own terraform and startup script from what's available in the
module.

**Comment by pdutch** [comment]
FYI, while it would be interesting to understand why this is an issue, I believe the problem lies with some of the python dependencies. I've since provided the forseti server a proxy to get outbound internet access, which removed the need to use the artifactory mirror for python dependencies, and the issue is now resolved. Something to bear in mind however would be a way to deploy forseti without external dependencies. I've been looking into the GKE version, and hopefully the containers for that are fully self contained (other than policy files).

**Comment by blueandgold** [comment]
Hi @pdutch glad that you were able to find a workaround for the VM version.  Yes, that will rely on external access to the internet to install the packages.  But you are correct that the GKE container images will have everything all bundled together.  I'm going to close this issue, if you have any other questions about this, please feel free to reopen.
