### ISSUE TITLE
[v2.23.0] Google SCC notifier doesn't work, 500 error

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3425]
Terraform module v5.0.0 + Forseti v2.23.0 on GCE.

My notifier run fails every time ~4 hours after start according to the log:

```python
2019-10-27 18:50:47,859 INFO [forseti-security][2.23.0] google.cloud.forseti.notifier.notifiers.cscc_notifier(run): Running Cloud Security Command Center notification module.
2019-10-27 22:54:53,175 ERROR [forseti-security][2.23.0] google.cloud.forseti.services.notifier.service(_run_notifier): <HttpError 500 when requesting https://securitycenter.googleapis.com/v1/organization
s/123456789000/sources/1234567890001112223/findings?alt=json&pageToken=CusC3cy7qgAx8QqflqlfsMwLpOnD9w5itomdonX0K1oIF9Brwj8Uztlw9lYqWvw9airRnWuQUWwnucxru6Mm1ydP3pxRVGEUuePu6mj4WTsZuhYEYXO94-KsIMJdvCOyGy-QG
hY9b1EZHoFwdD-_8gAwFcoWCLafn0DCBBg8L8ICJDhItQuBASTNtQEL8J3TUi0ocpjKmt3gwsI9f0aygXMTxsT5OSmdca0-OJaoFcOPLVaXZbXjMjugvBSWlxxLVb3q-X3ZbzXe3-AhfWTRht3LLtF8d644ywr5BTKQ_8qhAIIyjKCtaSDStoimQEGw5LFd6cW4ZSF6pgIM9
CbYJGjt-vkNhMmmuOwP8JuZDFRxestHXhFw0ZDZ0xmVF6hu4i3quvoFjlUZ4_EHI8vgaD2gE_behgFt-kgbj1daMIlE5hoZaaUQujRxKBULa4NgIXTQwxWU89aV8I-E38SyZMvwm5B1QUWwvvtDON5J returned "Internal error encountered.">
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/services/notifier/service.py", line 129, in _run_notifier
    self.service_config)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/notifier/notifier.py", line 187, in run
    .run(violations_as_dict, source_id=source_id))
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/cscc_notifier.py", line 285, in run
    self._send_findings_to_cscc(violations, source_id=source_id)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/cscc_notifier.py", line 229, in _send_findings_to_cscc
    for page in paged_findings_in_cscc:
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/gcp_api/repository_mixins.py", line 55, in list
    verb_arguments=arguments):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/gcp_api/_base_repository.py", line 467, in execute_paged_query
    response = self._execute(request)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/util/replay.py", line 169, in replay_wrapper
    return f(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/util/replay.py", line 82, in record_wrapper
    return f(self, request, *args, **kwargs)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/gcp_api/_base_repository.py", line 541, in _execute
    num_retries=self._num_retries)
  File "/home/ubuntu/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/http.py", line 855, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://securitycenter.googleapis.com/v1/organizations/123456789000/sources/1234567890001112223/findings?alt=json&pageToken=CusC3cy7qgAx8Qq
flqlfsMwLpOnD9w5itomdonX0K1oIF9Brwj8Uztlw9lYqWvw9airRnWuQUWwnucxru6Mm1ydP3pxRVGEUuePu6mj4WTsZuhYEYXO94-KsIMJdvCOyGy-QGhY9b1EZHoFwdD-_8gAwFcoWCLafn0DCBBg8L8ICJDhItQuBASTNtQEL8J3TUi0ocpjKmt3gwsI9f0aygXMTxsT
5OSmdca0-OJaoFcOPLVaXZbXjMjugvBSWlxxLVb3q-X3ZbzXe3-AhfWTRht3LLtF8d644ywr5BTKQ_8qhAIIyjKCtaSDStoimQEGw5LFd6cW4ZSF6pgIM9CbYJGjt-vkNhMmmuOwP8JuZDFRxestHXhFw0ZDZ0xmVF6hu4i3quvoFjlUZ4_EHI8vgaD2gE_behgFt-kgbj1d
aMIlE5hoZaaUQujRxKBULa4NgIXTQwxWU89aV8I-E38SyZMvwm5B1QUWwvvtDON5J returned "Internal error encountered.">
```

As a result I never see any event updates in Google SCC.

As per @hshin-g suggestion, I've decreased the number of calls for `securitycenter_max_calls` to `10`  in the `notifier` section (https://github.com/forseti-security/terraform-google-forseti/blob/e3ed110e80ee42b87f6ede1fa348c139d479dd1f/modules/server_config/templates/configs/forseti_conf_server.yaml.tpl#L277) and re-run the notifier, I'll report if that will help.

**Comment by kevensen** [comment]
Original issue.  https://github.com/forseti-security/terraform-google-forseti/issues/360

**Comment by gkowalski-google** [comment]
@red2k18 Can you please look into this to understand what the root cause is? Is this effecting everyone?

**Comment by kevensen** [comment]
@hshin-g should have some background too

**Comment by paskal** [comment]
Since the report findings were uploaded to SCC at least once (on November 19), no logs, unfortunately.

**Comment by red2k18** [comment]
@paskal Sorry to hear that. Thanks for your patience! Could you provide me an estimate of the number of violations in your environment?

**Comment by paskal** [comment]
Around 1000 at current moment, and historically at some point in time there were 40k of them.

**Comment by red2k18** [comment]
Thanks @paskal! Are those 1000 violations ACTIVE? You can double check by running `select count(*) from violations;`. You have mentioned that findings were uploaded to CSCC on November 19th. Are you still seeing this issue or findings are being uploaded to CSCC regularly?

**Comment by red2k18** [comment]
Hi @paskal, let's retrieve the number of ACTIVE violations in your organization as follows:

1. Retrieve the latest `scanner_index_id` by running `SELECT DISTINCT created_at_datetime, scanner_index_id FROM forseti_security.violations order by created_at_datetime DESC;`. You want to grab the `scanner_index_id` from row 1 as that corresponds to your latest scan.

2. Plug in the `scanner_index_id` retrieved in the above step in the following query to find out the number of ACTIVE violations.
`select count(*) from violations where scanner_index_id=<SCANNER_INDEX_ID>;`

Looking forward to hearing from you.

Thanks,
Rehana

**Comment by paskal** [comment]
@red2k18 I've had around 1000 ACTIVE violations after November 19th: no updates since then, Forseti hasn't been able to update security findings in SCC since then.

Where should I run these queries?

**Comment by red2k18** [comment]
@paskal Thanks for your response. Since 1000 active violations were sent to CSCC once, let's 
figure out why it's not being updated. Below are the two ways in which you can connect to MySQL to run the queries provided.

1. Forseti stores data in Cloud SQL database. You can connect to the Cloud SQL instance by using Cloud SQL proxy by following the instructions [here](https://forsetisecurity.org/docs/latest/develop/dev/setup.html#setting-up-cloud-sql), and if you choose to use MySQL Workbench you can run these queries there. 

2. Alternatively, you can SSH into your server VM, install MySQL client by running `sudo apt-get install mysql-client` and connect to MySQL through localhost by running `mysql -u root --host 127.0.0.1 --database forseti_security`.  You can then run the queries provided earlier.

Could you also enable debug logs by running `forseti server log_level set debug` and reload the config by running `forseti server configuration reload`?

Please run scanner again, grab the index id and run `forseti notifier run --scanner_index_id<SCANNER_INDEX_ID>`. Check the logs for error messages or relevant info.

If you do not wish to run the scanner again, please plug in the latest scanner index retrieved from the queries provided earlier and run `forseti notifier run --scanner_index_id<SCANNER_INDEX_ID>` and share the results.

Let me know if you have any questions.

Thanks,
Rehana

**Comment by paskal** [comment]
Now I found out that Forseti is stuck on November, 21. I'll kill the current run and re-start it with debug logging.

```
ubuntu@forseti-server-vm:~$ ps auxf | grep forseti -C1
root     19259  0.0  0.0  59220  3072 ?        S    Nov21   0:00  \_ /usr/sbin/CRON -f
ubuntu   19260  0.0  0.0   4624   916 ?        Ss   Nov21   0:00      \_ /bin/sh -c (/usr/bin/flock -n /home/ubuntu/forseti-security/forseti_cron_runner.lock /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh -b forseti-server-6e43eb0 || echo '[forseti-security] Warning: New Forseti cron job will not be started, because previous Forseti job is still running.') 2>&1 | logger
ubuntu   19261  0.0  0.0   4624    88 ?        S    Nov21   0:00          \_ /bin/sh -c (/usr/bin/flock -n /home/ubuntu/forseti-security/forseti_cron_runner.lock /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh -b forseti-server-6e43eb0 || echo '[forseti-security] Warning: New Forseti cron job will not be started, because previous Forseti job is still running.') 2>&1 | logger
ubuntu   19263  0.0  0.0  12180   888 ?        S    Nov21   0:00          |   \_ /usr/bin/flock -n /home/ubuntu/forseti-security/forseti_cron_runner.lock /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh -b forseti-server-6e43eb0
ubuntu   19264  0.0  0.0  13308  3232 ?        S    Nov21   0:00          |       \_ /bin/bash /home/ubuntu/forseti-security/install/gcp/scripts/run_forseti.sh -b forseti-server-6e43eb0
ubuntu   19876  0.0  0.1 492028 47088 ?        Sl   Nov21   9:41          |           \_ /usr/bin/python3 /usr/local/bin/forseti inventory create --import_as 20191121T165908
ubuntu   19262  0.0  0.0  34968  3192 ?        S    Nov21   0:28          \_ logger
--
ubuntu   17348  0.0  0.0  37948  3476 pts/0    R+   15:01   0:00                          \_ ps auxf
ubuntu   17349  0.0  0.0  14852  1068 pts/0    S+   15:01   0:00                          \_ grep --color=auto forseti -C1
_chrony   2542  0.0  0.0 101328  2620 ?        S    Nov19   0:00 /usr/sbin/chronyd
--
root     11273  1.8  0.4 8388732 133984 ?      Sl   Nov19 562:07  \_ /opt/google-fluentd/embedded/bin/ruby -Eascii-8bit:ascii-8bit /usr/sbin/google-fluentd --log /var/log/google-fluentd/google-fluentd.log --daemon /var/run/google-fluentd/google-fluentd.pid --under-supervisor
root     11997  0.3  0.0 115076 16244 ?        Ssl  Nov19  93:10 /usr/local/bin/cloud_sql_proxy -instances=forseti-security-tool:europe-west1:forseti-server-db-6e43eb0=tcp:3306
ubuntu   12108  1.6 53.0 22010672 16383268 ?   Ssl  Nov19 497:57 /usr/bin/python3 /usr/local/bin/forseti_server --endpoint [::]:50051 --forseti_db mysql+pymysql://root@127.0.0.1:3306/forseti_security?charset=utf8 --config_file_path /home/ubuntu/forseti-security/configs/forseti_conf_server.yaml --services explain inventory model scanner notifier
root     19678  0.0  0.0 1744152 24932 ?       Ssl  Dec04   0:36 /usr/lib/snapd/snapd

ubuntu@forseti-server-vm:~$ ll /var/log/forseti*
-rw-r----- 1 ubuntu root         0 Nov 22 06:25 /var/log/forseti.log
-rw-r----- 1 ubuntu root 237972855 Nov 21 19:51 /var/log/forseti.log.1
-rw-r----- 1 ubuntu root 455198846 Nov 21 05:03 /var/log/forseti.log.2
-rw-r--r-- 1 ubuntu root 227623498 Nov 20 05:03 /var/log/forseti.log.3
```
Along latest log entries in `/var/log/forseti.log.1` I see following:
```
2019-11-21 18:04:22,975 ERROR [forseti-security][2.24.0] google.cloud.forseti.services.inventory.base.resources(accept): Exception raised processing GsuiteGroup<data="{"adminCreated": true, "description":
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 24] Too many open files

<...>
oogle.auth.exceptions.TransportError: HTTPSConnectionPool(host='iam.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/-/serviceAccounts/forseti-server-gcp@forseti-security-tool.iam.gserviceaccount.com:signBlob?alt=json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6bd3959358>: Failed to establish a new connection: [Errno 24] Too many open files',))
```

**Comment by paskal** [comment]
>     1. Retrieve the latest `scanner_index_id` by running `SELECT DISTINCT created_at_datetime, scanner_index_id FROM forseti_security.violations order by created_at_datetime DESC;`. You want to grab the `scanner_index_id` from row 1 as that corresponds to your latest scan.
> 
>     2. Plug in the `scanner_index_id` retrieved in the above step in the following query to find out the number of ACTIVE violations.
>        `select count(*) from violations where scanner_index_id=<SCANNER_INDEX_ID>;`
> 

```
mysql> SELECT DISTINCT created_at_datetime, scanner_index_id FROM forseti_security.violations order by created_at_datetime DESC limit 1;
+---------------------+------------------+
| created_at_datetime | scanner_index_id |
+---------------------+------------------+
| 2019-11-19 07:13:12 | 1574147188195091 |
+---------------------+------------------+
mysql> select count(*) from violations where scanner_index_id=1574147188195091;
+----------+
| count(*) |
+----------+
|     1110 |
+----------+
```

**Comment by blueandgold** [comment]
Hi @paskal , thanks for updates.  I'm Henry on the Forseti team at Google.  I think there are a few things happening here.  Would it be possible for you to share the `/var/log/forseti.log.1` file that has the ` [Errno 24] Too many open files` errors?  Perhaps upload it to a GCS bucket.  Please direct message me and I can tell you my email.  Are you also on [our slack](https://forsetisecurity.slack.com/)?  If yes, please slack me (Henry Chang) on the #general channel.

Thanks!

**Comment by paskal** [comment]
@red2k18 still error 500, what I see in the log:
```
2019-12-10 15:36:03,414 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api.securitycenter(__init__): Initializing SecurityCenterRepositoryClient
2019-12-10 15:36:04,126 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api.securitycenter(__init__): Creating _SecurityCenterOrganizationsFindingsRepositoryClient
2019-12-10 15:36:07,380 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 1
2019-12-10 15:36:12,383 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 2
2019-12-10 15:36:17,808 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 3
2019-12-10 15:36:24,238 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 4
2019-12-10 15:36:30,971 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 5
<...>
2019-12-10 19:41:12,577 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 2625
2019-12-10 19:41:18,245 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 2626
2019-12-10 19:41:22,893 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 2627
2019-12-10 19:41:27,869 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 2628
2019-12-10 19:41:32,749 DEBUG [forseti-security][2.24.0] google.cloud.forseti.common.gcp_api._base_repository(execute_paged_query): Executing paged request # 2629
2019-12-10 19:42:32,619 ERROR [forseti-security][2.24.0] google.cloud.forseti.services.notifier.service(_run_notifier): <HttpError 500 when requesting https://securitycenter.googleapis.com/v1/organizations/123456789000/sources/1234567890001112223/findings?alt=json&pageToken=CvQC3cy7qgAx8QqfMdJr1gDB6aDPhGuzg-KcruNII3D4hTuCevSG7RcL95APW9U8ElKGrn9AaTbBvIg4WhqfM4D9K4g3HvMaI6BjD6N5-uYCB7ojL6jnR8raXzVbKj3bdenBcLJ1_y9rQuhQ1BS8Zr_jMlFw0UDmXlNPY_c2G3P9EOHH-91JrdPxE5mt0G468vIwU7x6GE092zueXfUrGzacg0lYmaqqKm7FWBzzotajfNmml17A9gtRMdTPT84v1CtRyMiUP129f6Ocmg_ZxpuTYdC5bDtElCi23-faOqVtib3qgd3wUDswJnF3aAmuG841tIw26FyRvSOS2Ih7T0hQAMLY27-5tilRyBiDr--W8MJlilTBLttCy6iObTRW6rrhBFux1meIdCbtg2zSmqpm1X5qCSCP4mm4tNsGOZRWz3DZVZh3fUpd50mx0Y6nbBd9K-EVh__dFY55Hodm1QsRnAj1AqhAXKtM51NbrNpNLagnXwCn returned "Internal error encountered.">
```
As I mentioned before, there is around 40k inactive findings from the same source.

If the issue is with what I think it is (requesting too many old findings to make sure to reopen ones that were already seen) then the quick fix solution would be request old findings only with latest event date newer than X (30 days, for example).

**Comment by paskal** [comment]
@blueandgold please drop me a message at `paskal.07@gmail.com`

**Comment by red2k18** [comment]
Hi @paskal, thanks again for your help to troubleshoot this issue. The findings generated in the last Forseti run will be checked to see if it is still active. Inactive findings will not be pulled every time you run scanner and notifier. So, if there are 1k active findings in your environment then the violations generated in the next run will be checked against 1k findings only. It is up to you to clear the old 40k inactive findings. I will look more into this and circle back. Thanks for your patience.

**Comment by red2k18** [comment]
Hi @paskal, thanks for sharing the log file. I wanted to let you know that I'm looking into it. Based on the logs, it seems that after processing 2628 pages, there is an authentication error due to which Notifier did not complete successfully. 

Is it possible for you to clear out INACTIVE findings by deleting all the violations from the database and start afresh by running scanner and notifier again? 

Even though it says authentication error, I'm pretty sure it is not due to Forseti-CSCC misconfiguration in your environment because 2628 pages were processed. 

Looking forward to hearing from you.

Thanks,
Rehana

**Comment by red2k18** [comment]
Hi @paskal, I'm working on a code fix that would retrieve only ACTIVE findings. That should fix this issue as we will not be retrieving 40k findings which are INACTIVE. I will let you when the fix is in. Please let me know if you have any questions. 

Thanks,
Rehana

**Comment by blueandgold** [comment]
Regarding the `OSError: [Errno 24] Too many open files`, I can reproduce with a low ulimit of 10 on the `ubuntu` user that runs Forseti.  Current ulimit for the `ubuntu` user is 1024, which seems low; we will raise this to be higher.

**Comment by paskal** [comment]
@blueandgold I've tried to re-start stuck command, but it became stuck without writing anything to logs.
I've killed it and re-enabled cron, I will wait for the first stuck run and then will apply ulimit change, kill stuck run and see if it will repeat.

**Comment by paskal** [comment]
@blueandgold sorry but I can't get Forseti work (or fail) without the `ulimit` fix so far: it is stuck without any log messages. My environment doesn't seem to be reliable at this moment to test the fix.

**Comment by blueandgold** [comment]
Hi @paskal, there should be some logs.  Can you please check stackdriver, focusing on the Forseti VM as in the screenshot below?  Can you also please reset the VM, let's double-check it setup correctly.  Please let me know what you see.  
![image](https://user-images.githubusercontent.com/6977544/70924846-15ac4180-1fdf-11ea-9c45-bca220475c50.png)
Thank you

**Comment by paskal** [comment]
I've re-set it few hours ago with Terraform module v5.2.0 and Forseti v2.25.0 and deleted DB to have a relatively fresh start, I will write as soon as I would be able to reproduce the issue and re-start my installation with higher `ulimit`.

**Comment by red2k18** [comment]
This issue will be closed only after the fix is released, and the issue is resolved in user's environment.

**Comment by red2k18** [comment]
Closing this issue as the fix is merged in the codebase.
