### ISSUE TITLE
Config Validator crashing during scan

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3552]
## Story
A [user](https://forsetisecurity.slack.com/archives/CAZCH95EF/p1576088198369000) is trying to use Config Validator with Forseti on GCE v2.24.0 on a large GCP org (almost 1TB CAI export) and it appears that CV is crashing. The machine type is the standard n1-standard-8. 

The user attempted to use all of the CV Policy samples and they get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py", line 119, in run
    scanner.run()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 183, in run
    for flattened_violations in self._retrieve_flattened_violations():
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 164, in _retrieve_flattened_violations
    for violations in self.validator_client.paged_review(cv_assets):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 114, in paged_review
    violations = self.review(paged_assets)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 696, in reraise
    raise value
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 185, in review
    LOGGER.exception('ConfigValidatorAuditError: %s', e.message)
AttributeError: '_Rendezvous' object has no attribute 'message'
```

@gkowalski-google has worked with the user and verified the Terraform configuration is correct and the CV service is healthy (before and after a scan). The user has tested with using just a single constraint and the issue went away. They are going to do some "binary search" to see where the issue lies; first with testing with half of the constraints. We will try to determine if the issue is a specific constraint(s) or if it is the number of constraints.

**Comment by gkowalski-google** [comment]
Attempted to reproduce using current version of FCV in use by Forseti, and the latest version of CV, in conjunction with all of the samples. This used to repro for me, but not anymore. I believe this was due to some issues with one or more templates. Closing for now and will re-open if necessary.
