### ISSUE TITLE
InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'XXXXXXX'")

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/forseti-security#3619]
When the server VM starts, there are several `Duplicate column name` errors, for example:-

<img width="922" alt="Screen Shot 2020-01-31 at 10 34 56 PM" src="https://user-images.githubusercontent.com/6835135/73586930-296e1300-447a-11ea-85e8-c9a87a03a6b4.png">

Here's one of the sample stacktrace:-

```
Traceback (most recent call last):
  File "/home/ubuntu/forseti-security/install/gcp/upgrade_tools/db_migrator.py", line 165, in _create_or_drop_columns
    column)
  File "/home/ubuntu/forseti-security/install/gcp/upgrade_tools/db_migrator.py", line 54, in create_column
    column.create(table, populate_default=True)
  File "/home/ubuntu/forseti-security/.eggs/sqlalchemy_migrate-0.11.0-py3.6.egg/migrate/changeset/schema.py", line 577, in create
    engine._run_visitor(visitorcallable, self, connection, **kwargs)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2011, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1599, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/ubuntu/forseti-security/.eggs/sqlalchemy_migrate-0.11.0-py3.6.egg/migrate/changeset/ansisql.py", line 56, in traverse_single
    ret = super(AlterTableVisitor, self).traverse_single(elem)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 130, in traverse_single
    return meth(obj, **kw)
  File "/home/ubuntu/forseti-security/.eggs/sqlalchemy_migrate-0.11.0-py3.6.egg/migrate/changeset/ansisql.py", line 104, in visit_column
    self.execute()
  File "/home/ubuntu/forseti-security/.eggs/sqlalchemy_migrate-0.11.0-py3.6.egg/migrate/changeset/ansisql.py", line 44, in execute
    return self.connection.execute(self.buffer.getvalue())
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 974, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1147, in _execute_text
    parameters,
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'violation_message'") [SQL: '\nALTER TABLE violations ADD violation_message TEXT'] (Background on this error at: http://sqlalche.me/e/2j85)
```

I'm using v5.1.0.

Thank you.

**Comment by choonchernlim** [comment]
I don't believe it causes any problem based on my high level testing. But, just like you mentioned, I want to make sure the captured logs won't have too many false positives, which makes it hard to debug real problems in the future.

Since this issue is handled, I'll close it and wait for the future release.
