### ISSUE TITLE
Forseti requests[security] version conflicts

### ISSUE THREAD

**Issue by xingao267** [forseti-security/forseti-security#3760]
Tested with current Terraform Forseti module at head, commit cf59de4

Got this error at forset startup

Traceback (most recent call last):
  File "/usr/local/bin/forseti", line 30, in <module>
    sys.exit(load_entry_point('forseti-security==2.25.1', 'console_scripts', 'forseti')())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2461, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2484, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (requests 2.23.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('requests[security]==2.21.0'))

**Comment by xingao267** [comment]
@gkowalski-google ptal whenever you get a chance

**Comment by gkowalski-google** [comment]
Hi @xingao267, sorry for the delay. I did look into this, but I was not able to repro. Can you provide any specifics about how you are running into this error?

**Comment by xingao267** [comment]
@gkowalski-google thanks for looking into this, it seems this error might be just a one-off or fixed from upstream.

Now I'm getting a different error when the forseti scan run invokes config validator. You can probably reproduce it by manually triggering a `forseti scan run` with config validator enabled.

```
[forseti-security][2.25.1] google.cloud.forseti.scanner.scanner(run): Error running scanner: ConfigValidatorScanner: 'Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 196, in reset self.stub.Reset(validator_pb2.ResetRequest()) File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 565, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with: status = StatusCode.INTERNAL details = "Not supported" debug_error_string = "{"created":"@1593613332.600850846","description":"Error received from peer ipv6:[::1]:50052","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Not supported","grpc_status":13}" > During handling of the above exception, anothe Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 196, in reset self.stub.Reset(validator_pb2.ResetRequest()) File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 565, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with: status = StatusCode.INTERNAL details = "Not supported" debug_error_string = "{"created":"@1593613332.600850846","description":"Error received from peer ipv6:[::1]:50052","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Not supported","grpc_status":13}" > During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanner.py", line 119, in run scanner.run() File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 203, in run for flattened_violations in self._retrieve_flattened_violations(): File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 178, in _retrieve_flattened_violations self.validator_client.reset() File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f return Retrying(*dargs, **dkw).call(f, *args, **kw) File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 206, in call return attempt.get(self._wrap_exception) File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get six.reraise(self.value[0], self.value[1], self.value[2]) File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise raise value File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call attempt = Attempt(fn(*args, **kwargs), attempt_number, False) File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 203, in reset raise errors.ConfigValidatorResetError(e) google.cloud.forseti.scanner.scanners.config_validator_util.errors.ConfigValidatorResetError: <_Rendezvous of RPC that terminated with: status = StatusCode.INTERNAL details = "Not supported" debug_error_string = "{"created":"@1593613332.600850846","description":"Error received from peer ipv6:[::1]:50052","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Not supported","grpc_status":13}" >
```

**Comment by gkowalski-google** [comment]
@xingao267 Are you using Forseti v2.25.1 or the main branch? In Forseti v2.25.1 there is a call to Config Validator to reset, which is no longer needed or supported in later versions of CV. This call was [removed from Forseti in April](https://github.com/forseti-security/forseti-security/pull/3725). If you need to use a later version of CV, then you'll need to use the main branch of Forseti or at least a commit after that PR.

**Comment by xingao267** [comment]
I switched the `forseti_version` to `master` in the module call, and got the following error:

```
  "serverMessage": "Error running scanner: ConfigValidatorScanner: 'Traceback
(most recent call last):\n  File
\"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py\",
line 176, in review\n    return self.stub.Review(review_request).violations\n
File \"/usr/local/lib/python3.6/dist-packages/grpc/_channel.py\", line 565, in
__call__\n    return _end_unary_response_blocking(state, call, False, None)\n
File \"/usr/local/lib/python3.6/dist-packages/grpc/_channel.py\", line 467, in
_end_unary_response_blocking\n    raise _Rendezvous(state, None, None,
deadline)\ngrpc._channel._Rendezvous: <_Rendezvous of RPC that terminated
with:\n\tstatus = StatusCode.INTERNAL\n\tdetails = \"Received RST_STREAM with
error code 2\"\n\tdebug_error_string =
\"{\"created\":\"@1593734664.508265031\",\"description\":\"Error received from
peer
ipv6:[::1]:50052\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1052,\"grpc_message\":\"Received
RST_STREAM with error code 2\",\"grpc_status\":13}\"\n>\n\nDuring handling of
the above exception, another exception occurred:\n\nTraceback (most recent call
last):\n  File
\"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanner.py\",
line 119, in run\n    scanner.run()\n  File
\"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py\",
line 200, in run\n    for flattened_violations in
self._retrieve_flattened_violations():\n  File
\"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py\",
line 180, in _retrieve_flattened_violations\n    for violations in
self.validator_client.paged_review(cv_assets):\n  File
\"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py\",
line 122, in paged_review\n    violations = self.review(paged_assets)\n  File
\"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\",
line 49, in wrapped_f\n    return Retrying(*dargs, **dkw).call(f, *args,
**kw)\n  File
\"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\",
line 206, in call\n    return attempt.get(self._wrap_exception)\n  File
\"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\",
line 247, in get\n    six.reraise(self.value[0], self.value[1],
self.value[2])\n  File \"/usr/local/lib/python3.6/dist-packages/six.py\", line
703, in reraise\n    raise value\n  File
\"/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py\",
line 200, in call\n    attempt = Attempt(fn(*args, **kwargs), attempt_number,
False)\n  File
\"/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py\",
line 183, in review\n    raise
errors.ConfigValidatorAuditError(e)\ngoogle.cloud.forseti.scanner.scanners.config_validator_util.errors.ConfigValidatorAuditError:
<_Rendezvous of RPC that terminated with:\n\tstatus =
StatusCode.INTERNAL\n\tdetails = \"Received RST_STREAM with error code
2\"\n\tdebug_error_string =
\"{\"created\":\"@1593734664.508265031\",\"description\":\"Error received from
peer
ipv6:[::1]:50052\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1052,\"grpc_message\":\"Received
RST_STREAM with error code 2\",\"grpc_status\":13}\"\n>\n'"
```

**Comment by PeterYou** [comment]
Hi @xingao267 , I got the same error for a while:
To fix it:
change The target field from "organizations/**" ------> "organization/*"
The change is remove the "s" at the end of organizations and the one of the starts

**Comment by gkowalski-google** [comment]
@xingao267 Any update on this? I have been doing some testing with the latest patch release (2.25.2) and I didn't have any issues with CV. It seems like you need this glob support, which will be available with v2.26.0.

**Comment by xingao267** [comment]
I tried the main branch and got some other error a while ago, and didn't got bandwidth to debug it further. I'll try with the next Forseti release version. Yes, I do need the proper CV glob support (https://github.com/forseti-security/config-validator/issues/142 and https://github.com/forseti-security/config-validator/issues/145). Will those be included in v2.25.2? If not, when will v2.26.0 be released?

**Comment by gkowalski-google** [comment]
The v2.25.2 patch release will just contain the fixes for the model creation. Current estimate for v2.26.0 is the 2nd half of August.

**Comment by xingao267** [comment]
@gkowalski-google thanks for the update. good to know. I can wait for the v2.26.0 version or try with main branch again when I get a chance.

**Comment by gkowalski-google** [comment]
@xingao267 I am able to reproduce the error you saw with the `Received RST_STREAM  with error code 2`. More details on this bug: https://github.com/forseti-security/forseti-security/issues/3798.

**Comment by gkowalski-google** [comment]
@xingao267 Do you want to use this ticket to track that Forseti v2.26.0 supports the glob target matching?

**Comment by xingao267** [comment]
@gkowalski-google i'm not using this ticket to keep track of Forseti v2.26.0 supporting glob target matching. We can close this, and I'll use #3798 to keep track of the other issue.
