### ISSUE TITLE
Forseti Inventory Fails when attempting to run against Single Project 

### ISSUE THREAD

**Issue by pythian-loronk** [forseti-security/forseti-security#3823]
Hello,

I am attempting to run Forseti in a single project only.  I have downloaded / deployed Forseti via the Terraform deployment (https://github.com/forseti-security/forseti-security).  Prior to deploying, I ensured I changed the `composite_root_resources` variable to be my `project/<project-id`.  As a side note, I also changed this configuration line directly in the `forseti_server_config.yaml` to be `project/<project-number>` but still am having the same issue.  When I attempt to run `sh run_foresti.sh` or when I attempt to run the `forseti inventory create` command manually, the inventory just hangs forever before I force kill the process.  Please see console output below:

Shell `run_forseti.sh` run:
```
run_forseti.sh: 16: run_forseti.sh: source: not found
+ sudo rm -rf /tmp/forseti-cai-*
+ sudo gsutil cp gs://forseti-server-<ID>/configs/forseti_conf_server.yaml /forseti-security/configs/forseti_conf_server.yaml
Copying gs://forseti-server-<ID>/configs/forseti_conf_server.yaml...
/ [1 files][ 20.7 KiB/ 20.7 KiB]
Operation completed over 1 objects/20.7 KiB.
+ sudo gsutil cp -r gs://forseti-server-<ID>/rules /forseti-security/
Copying gs://forseti-server-<ID>/rules/audit_logging_rules.yaml...
Copying gs://forseti-server-<ID>/rules/bigquery_rules.yaml...
Copying gs://forseti-server-<ID>/rules/blacklist_rules.yaml...
Copying gs://forseti-server-<ID>/rules/bucket_rules.yaml...
/ [4 files][  5.4 KiB/  5.4 KiB]
==> NOTE: You are performing a sequence of gsutil operations that may
run significantly faster if you instead use gsutil -m cp ... Please
see the -m section under "gsutil help options" for further information
about when gsutil -m can be advantageous.

Copying gs://forseti-server-<ID>/rules/cloudsql_rules.yaml...
Copying gs://forseti-server-<ID>/rules/enabled_apis_rules.yaml...
Copying gs://forseti-server-<ID>/rules/external_project_access_rules.yaml...
Copying gs://forseti-server-<ID>/rules/firewall_rules.yaml...
Copying gs://forseti-server-<ID>/rules/forwarding_rules.yaml...
Copying gs://forseti-server-<ID>/rules/group_rules.yaml...
Copying gs://forseti-server-<ID>/rules/groups_settings_rules.yaml...
Copying gs://forseti-server-<ID>/rules/iam_rules.yaml...
Copying gs://forseti-server-<ID>/rules/iap_rules.yaml...
Copying gs://forseti-server-<ID>/rules/instance_network_interface_rules.yaml...
Copying gs://forseti-server-<ID>/rules/ke_rules.yaml...
Copying gs://forseti-server-<ID>/rules/ke_scanner_rules.yaml...
Copying gs://forseti-server-<ID>/rules/kms_rules.yaml...
Copying gs://forseti-server-<ID>/rules/lien_rules.yaml...
Copying gs://forseti-server-<ID>/rules/location_rules.yaml...
Copying gs://forseti-server-<ID>/rules/log_sink_rules.yaml...
Copying gs://forseti-server-<ID>/rules/resource_rules.yaml...
Copying gs://forseti-server-<ID>/rules/retention_rules.yaml...
Copying gs://forseti-server-<ID>/rules/role_rules.yaml...
Copying gs://forseti-server-<ID>/rules/service_account_key_rules.yaml...
\ [24 files][ 45.1 KiB/ 45.1 KiB]
Operation completed over 24 objects/45.1 KiB.
+ [ false != true ]
+ sudo gsutil -m rsync -d -r gs://forseti-server-<ID>/policy-library /policy-library/policy-library
CommandException: arg (gs://forseti-server-<ID>/policy-library) does not name a directory, bucket, or bucket subdir.
+ sudo systemctl restart config-validator
+ [ ! -f /forseti-security/configs/forseti_conf_server.yaml ]
+ forseti server configuration reload
{
  "isSuccess": true,
  "errorMessage": ""
}
+ forseti config format json
{'endpoint': 'localhost:50051', 'model': '', 'format': 'json'}
+ forseti config delete model
{'endpoint': 'localhost:50051', 'model': '', 'format': 'json'}
+ forseti inventory purge
{
  "result": "Purge is disabled.  Nothing will be purged."
}
+ /bin/date -u +%Y%m%dT%H%M%S
+ MODEL_NAME=20200918T184759
+ echo Running Forseti inventory.
Running Forseti inventory.
+ forseti inventory create --import_as 20200918T184759
^CTraceback (most recent call last):
  File "/usr/local/bin/forseti", line 33, in <module>
    sys.exit(load_entry_point('forseti-security==2.25.1', 'console_scripts', 'forseti')())
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/stubs.py", line 34, in RunForsetiCli
    forseti_cli.main()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/services/cli.py", line 1193, in main
    services[config.service](client, config, output, config_env)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/services/cli.py", line 891, in run_inventory
    actions[config.action]()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/services/cli.py", line 861, in do_create_inventory
    config.enable_debug):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 349, in _next
    self._state.condition.wait()
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

Manual Run:
```
ubuntu@forseti-server-vm-<ID>:~$ forseti inventory create
^CTraceback (most recent call last):
  File "/usr/local/bin/forseti", line 33, in <module>
    sys.exit(load_entry_point('forseti-security==2.25.1', 'console_scripts', 'forseti')())
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/stubs.py", line 34, in RunForsetiCli
    forseti_cli.main()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/services/cli.py", line 1193, in main
    services[config.service](client, config, output, config_env)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/services/cli.py", line 891, in run_inventory
    actions[config.action]()
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.25.1-py3.6.egg/google/cloud/forseti/services/cli.py", line 861, in do_create_inventory
    config.enable_debug):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 349, in _next
    self._state.condition.wait()
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

I have also verified all permissions are correct on my Foresti Service Account including the `Cloud Audit Viewer` permission.  Is there something else I may be missing that could cause this issue?  Let me know any information you need that may be helpful. 

Thank you for any assistance!

**Comment by ekisu** [comment]
For anyone that comes across this, using `projects/<project number>` and not `projects/<project id>` and restarting the Forseti server worked for me. It seems this is caused because it tries to fetch the project from the assets exported from the Cloud Asset Inventory, and it attempts to find it as `//cloudresourcemanager.googleapis.com/projects/<project id>`, but the assets are always in the format `//cloudresourcemanager.googleapis.com/projects/<project number>`.
