### ISSUE TITLE
Groups scanner can't read rules file from bucket

### ISSUE THREAD

**Issue by carise** [forseti-security/forseti-security#634]
https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/google/cloud/security/scanner/scanners/groups_scanner.py#L290

Groups scanner assumes that the file is local, but the config might specify a file stored in GCS.

Error:

```
2017-09-12 10:04:23,249 __main__     ERROR    main Error running scanner: GroupsScanner
Traceback (most recent call last):
  File "<snip>/forseti_security-1.1.3-py2.7.egg/google/cloud/security/scanner/scanner.py", line 114, in main
    scanner.run()
  File "<snip>/forseti_security-1.1.3-py2.7.egg/google/cloud/security/scanner/scanners/groups_scanner.py", line 290, in run
    with open(self.rules, 'r') as f:
IOError: [Errno 2] No such file or directory: 'gs://MY_BUCKET/rules/group_rules.yaml'
```

**Comment by mirons-google** [comment]
@blueandgold to review
